app_name = "Fast Stream Bot"
env_file = ".env"
header_image = "https://i.ibb.co/NH9ZkZD/photo-2026-04-06-18-50-05-7625720507131756560.jpg"

max_credits = 500
min_credits_required = 5
initial_credits = 50
increment_credits = 10
decrement_credits = 10
enable_shortener = true